### ISSUE TITLE
Add timeout as user configurable field

### ISSUE THREAD

**Issue by workingmanrob** [pszafer/epson_projector#9]
Hey first of all thanks for making this in the first place and now for the integration.

Super easy to set it up now.

Unfortunately it still seems to timeout after 10 seconds and does not retry so I am still forced to edit the code by hand after any hass updates.

I know the kodi media player supports this configurable timeout value since I had problems with the 5 second default there.  Once I set 30 seconds as the timeout it always connects.

                "version": 1,
                "domain": "kodi",
                "title": "Kodi",
                "data": {
                    "name": "kodi",
                    "host": "kodi.local",
                    "port": 8080,
                    "ws_port": 9090,
                    "username": null,
                    "password": null,
                    "ssl": false,
                    "timeout": 30

To workaround this I now edit 2 files.  I changed main and it worked but then it didn't so I changed projector_tcp as well and it seems to work.

epson_projector/main.py - timeout_scale=1.0 -> timeout_scale=3.0
epson_projector/projector_tcp.py - async_timeout.timeout(10) -> async_timeout.timeout(30)

Restart hass and my projector is back.

**Comment by pszafer** [comment]
Hi, please fill an issue in Home Assistant Core issues. I will be automatically tagged and then I'm gonna have some arguments to convince Baloob for allowing me to add timeout as configurable option (I have code ready for this).

**Comment by workingmanrob** [comment]
Ok will do.

Closing this..
